import EncounterFormImportResult from "./flow/EncounterFormImportResult";

export interface DataAnomaly {
    facilityId: number,
    facilityName: string,
    patientMrn: string,
    encounterNumber: string,
    encounterFormId: number,
    anesCaseTyp: string,
    surgeonProvider: string,
    anesProviders: string[],
    formTitle: string,
    formCompletePct: number,
    formCreatedOn: Date,
    formCreatedByName: string,
    importResult: EncounterFormImportResult,
    anomalyCount: number,
    dateOfService: string,
    providerArrivalTimestamp: Date,
    scheduledStartTimestamp: Date,
    anesthesiaStartTimestamp: Date,
    anesthesiaReadyTimestamp: Date,
    surgeryStartTimestamp: Date,
    surgeryEndTimestamp: Date,
    pacuArrivalTimestamp: Date,
    anesthesiaEndTimestamp: Date,
    epiduralStartTimestamp: Date,
    epiduralEndTimestamp: Date,
    providerArrivalMins: number,
    totalAnesthesiaMins: number,
    totalAnesthesiaReadyMins: number,
    totalSurgeryPrepMins: number,
    totalSurgeryMins: number,
    totalEmergenceMins: number,
    totalEpiduralMins: number
}